[package]
name = "check-dupes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha256 = "1.0.3"
walkdir = "2.3.2"
md5 = "0.7.0"
rayon = "1.5.3"
prettytable-rs = "0.8.0"
